<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bddTweet [
<!ELEMENT bddTweet (tweet*, user*)>
<!ELEMENT tweet (date,metadata?,body, reponses*)>
<!ATTLIST tweet idT ID #REQUIRED>
<!ATTLIST tweet idRefUser IDREF #REQUIRED>
<!ATTLIST tweet idRetweet IDREF #IMPLIED>
<!ELEMENT date (#PCDATA)>
<!ELEMENT metadata (media?,location?,userConfig?)>
<!ELEMENT media (url+)>
<!ELEMENT url (#PCDATA)>

<!ELEMENT location (gps?,city?,country?)>
<!ELEMENT gps (lat,long)>
<!ELEMENT lat (#PCDATA)>
<!ELEMENT long (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT userConfig (version)>
<!ATTLIST userConfig osType (Android|iOS|Windows|Linux|unknown|other) "unknown">
<!ELEMENT version (#PCDATA)>

<!ELEMENT body (formatting,language,retweets,author,content)>
<!ATTLIST body idOriginalTweet IDREF #IMPLIED>

<!ELEMENT formatting (fontsize,fontcolor,font)>
<!ELEMENT fontsize (#PCDATA)>
<!ELEMENT fontcolor (#PCDATA)>
<!ELEMENT font (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT retweets (#PCDATA)>
<!ELEMENT author (name, userref)>
<!ATTLIST author idAuthor IDREF #REQUIRED>
<!ELEMENT name (#PCDATA)>

<!ELEMENT content (#PCDATA|url|hashtag|userref)*>

<!ELEMENT hashtag (#PCDATA)>

<!ELEMENT userref (#PCDATA)>

<!ELEMENT reponses (tweet)*>
<!ELEMENT user (nom+, prenom+)>
<!ATTLIST user idU ID #REQUIRED>
<!ATTLIST user idRefTweet IDREF #IMPLIED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
]>

<bddTweet>
	<tweet idT="t6666" idRefUser="u1">
		<date>2020-10-15T18:53:25</date>
		<body>
			<formatting>
				<fontsize></fontsize>
				<fontcolor></fontcolor>
				<font></font>
			</formatting>
			<language></language>
			<retweets>1</retweets>
			<author idAuthor="u1">
				<name></name>
				<userref></userref>
			</author>
			<content>
				.
				<userref>@exemple</userref>
				absolutely smashed it at
				<hashtag>#mtvlivelockdown</hashtag>
				! Catch hhim at the official
				<userref>@clubmtvuk</userref>
				after party tonight @ 10pm
			</content>
		</body>
			<reponses>
				<tweet idT="t5665" idRefUser="u2">
				<date>2020-10-16T13:48:32</date>
				<body>
					<formatting>
						<fontsize></fontsize>
						<fontcolor></fontcolor>
						<font></font>
					</formatting>
					<language></language>
					<retweets>0</retweets>
					<author idAuthor="u2">
						<name></name>
						<userref></userref>
					</author>
					<content>
						Nooope!
					</content>
				</body>
				</tweet>
	</reponses>
	</tweet>
		<tweet idT="t6226" idRefUser="u1">
		<date>2020-10-10T07:06:17</date>
		<body>
			<formatting>
				<fontsize></fontsize>
				<fontcolor></fontcolor>
				<font></font>
			</formatting>
			<language></language>
			<retweets>0</retweets>
			<author idAuthor="u1">
				<name></name>
				<userref></userref>
			</author>
			<content>
				I can assure
				<userref>@Alxxwi</userref>
				Looking around me,
				<hashtag>#I&lt;3XML</hashtag>
				We use a collection of XML
				<userref>@Cristophe</userref>
				. Its mission is to provide superior technology and expertise
			</content>
		</body>
	</tweet>
		<tweet idT="t6336" idRefUser="u3">
		<date>2020-10-01T12:14:53</date>
		<body>
			<formatting>
				<fontsize></fontsize>
				<fontcolor></fontcolor>
				<font></font>
			</formatting>
			<language></language>
			<retweets>0</retweets>
			<author idAuthor="u3">
				<name></name>
				<userref></userref>
			</author>
			<content>
				.
				<userref>@Cristophe</userref>
				Then I summarize the reasons for which it is an absolutely abominable film?
				<hashtag>#mtvlivelockdown</hashtag>
				Everything has to be absolutely above-board
				<userref>@Cristophe</userref>
				I needed to talk with someone who was very smart after party tonight @ 10pm
			</content>
			</body>

			<reponses>
				<tweet idT="t7226" idRefUser="u2">
					<date>2020-10-10T08:06:17</date>
					<body>
						<formatting>
							<fontsize></fontsize>
							<fontcolor></fontcolor>
							<font></font>
						</formatting>
						<language></language>
						<retweets>0</retweets>
						<author idAuthor="u1">
							<name></name>
							<userref></userref>
						</author>
						<content>
							This is just to say
						</content>
					</body>
				</tweet>
				<tweet idT="t7227" idRefUser="u3">
					<date>2020-10-10T09:06:17</date>
					<body>
						<formatting>
							<fontsize></fontsize>
							<fontcolor></fontcolor>
							<font></font>
						</formatting>
						<language></language>
						<retweets>0</retweets>
						<author idAuthor="u1">
							<name></name>
							<userref></userref>
						</author>
						<content>
							I have eaten
							the <hashtag>#plums</hashtag>
							that were in
							the icebox
						</content>
					</body>
				</tweet>
				<tweet idT="t7228" idRefUser="u1">
					<date>2020-10-10T10:06:17</date>
					<body>
						<formatting>
							<fontsize></fontsize>
							<fontcolor></fontcolor>
							<font></font>
						</formatting>
						<language></language>
						<retweets>0</retweets>
						<author idAuthor="u1">
							<name></name>
							<userref></userref>
						</author>
						<content>
							 and which
							 you were probably
							 saving
							 for breakfast
						</content>
					</body>
				</tweet>
			</reponses>
	</tweet>
	<tweet idT="t6446" idRefUser="u4" idRetweet="t6666">
		<date>2020-10-17T00:42:35</date>
		<body>
			<formatting>
				<fontsize></fontsize>
				<fontcolor></fontcolor>
				<font></font>
			</formatting>
			<language></language>
			<retweets>0</retweets>
			<author idAuthor="u4">
				<name></name>
				<userref></userref>
			</author>
			<content>
				She was quite aware of her own limitations
				<userref>@Jean</userref>
				Scotland coach Matt Williams is absolutely right
				<hashtag>#howTOuseAbsolutely</hashtag>
				All I know is what I read in the paper,
				<userref>@Alxxwi</userref>
				because of the authority he brings to it
			</content>
		</body>
	</tweet>
	<tweet idT="t6556" idRefUser="u4">
		<date>2020-10-13T11:23:46</date>
		<body>
			<formatting>
				<fontsize></fontsize>
				<fontcolor></fontcolor>
				<font></font>
			</formatting>
			<language></language>
			<retweets>0</retweets>
			<author idAuthor="u4">
				<name></name>
				<userref></userref>
			</author>
			<content>
				.
				<userref>@Jean</userref>
				I know where to go when
				<hashtag>#COVID19</hashtag>
				need new news. What about all those words and expressions
				<userref>@Cristophe</userref>
				?
			</content>
		</body>
	</tweet>
	<user idU="u1">
		<nom>Dupont</nom>
		<prenom>Jean</prenom>
	</user>
	<user idU="u2">
		<nom>Dupont</nom>
		<prenom>Christophe</prenom>
	</user>
	<user idU="u3">
		<nom>Mazrie</nom>
		<prenom>Emilie</prenom>
	</user>
	<user idU="u4">
		<nom>Alxxwi</nom>
		<prenom>Dupont</prenom>
	</user>
</bddTweet>
